name: CI
on: [push] #in what action that we want to run like (push,pr,merges)
jobs:
  standard-checks: 
    name: Lint and Test
    runs-on: ubuntu-latest

    steps:
    #  - run: node -v
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        #with: 
        #  node-version: "16.14.0"
    #  - run: node -v
      - name: Install packages
        run: npm ci #npm ci instead of npm i
      
      - name: Run ESlint
        run: npm run ci:lint 

      - name: run Tests
        run: npm run ci:test #we dont want to use --watch in github so we pass ci instead of npm t
      
      - name: Bundle and output
        run: npm run build


        #also I can use another job like for example Tests
        #but npm ci or npm i its gonna take too much time, because we use a node module for each job
        # the jobs works asyncronously so they work at the same time.
  #tests: 
  #  steps:
  #    - name: Checkout code
  #      uses: actions/checkout@v2
  #    
  #    - name: Install packages
  #      run: npm ci #npm ci instead of npm i
  #
  #    - name: run Tests
  #      run: npm run ci:test